<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="deg2rad" value="${pi/180}"/>
  <xacro:property name="rev2rad" value="${2*pi}"/>
  <xacro:property name="inch2m" value="${25.4/1000}"/>
  <xacro:property name="mm2m" value="${1/1000}"/>

  <xacro:macro name="cylinder_tube_link" params="name outer_radius inner_radius length density origin_offset mass=-1 material='StoglRobotics/LightGrey'">
    <!-- Length goes along z axis -->

      <link name="${name}">

        <xacro:if value="${mass == -1}">
          <xacro:property name="outer_area" value="${outer_radius * outer_radius * pi}"/>
          <xacro:property name="inner_area" value="${inner_radius * inner_radius * pi}"/>
          <xacro:property name="volume" value="${length * (outer_area - inner_area)}"/>
          <xacro:property name="mass" value="${volume * density}"/>
        </xacro:if>

        <visual>
          <origin xyz="0 0 ${origin_offset}" rpy="0 0 0"/>
          <geometry>
              <cylinder length="${length}" radius="${outer_radius}"/>
          </geometry>
          <material name="${material}"/>
        </visual>

        <collision>
          <origin xyz="0 0 ${origin_offset}" rpy="0 0 0"/>
          <geometry>
              <cylinder length="${length}" radius="${outer_radius}"/>
          </geometry>
        </collision>

        <xacro:cylinder_inertial length="${length}" outer_radius="${outer_radius}" inner_radius="${inner_radius}" mass="${mass}" origin_xyz="0 0 ${origin_offset}"/>

      </link>
  </xacro:macro>


  <xacro:macro name="rectangular_tube_link"
      params="name width length height wall_thickness density origin_offset mass=-1 material='StoglRobotics/LightGrey'"> -->

      <!-- Length goes along y, width goes along x, height goes along z -->

      <!-- length goes from hole to hole, while link_total_length goes from outer edge to outer edge. To center link around holes, add width/2 to both ends -->
      <xacro:if value="${mass == -1}">
        <xacro:property name="outer_area" value="${width * height}"/>
        <xacro:property name="inner_area" value="${(width - 2*wall_thickness) * (height - 2*wall_thickness)}"/>
        <xacro:property name="volume" value="${length * (outer_area - inner_area)}"/>
        <xacro:property name="mass" value="${volume * density}"/>
      </xacro:if>


      <link name="${name}">

        <!-- It may make more sense to have origin in center of thickness, but when you export as cade, usally is done from edge -->
        <visual>
            <origin xyz="0 ${origin_offset} ${height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${length} ${height}"/>
            </geometry>
            <material name="${material}"/>
        </visual>

        <collision>
            <origin xyz="0 ${origin_offset} ${height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${length} ${height}"/>
            </geometry>
        </collision>

        <xacro:solid_cuboid_inertial width="${width}" height="${length}" depth="${height}" mass="${mass}" origin_xyz="0 ${origin_offset} ${height/2}"/>
      </link>

  </xacro:macro>


  <xacro:macro name="rectangular_plate_link" params="name width length plate_thickness density origin_offset mass=-1 material='StoglRobotics/LightGrey'">
      <!-- Origin offset is usally length/2 or length/2 + width/2 + width/2  -->
      <!-- length goes from hole to hole, while link_total_length goes from outer edge to outer edge. To center link around holes, add width/2 to both ends -->

      <!-- Length goes along y, width goes along x, thickness goes along z -->

      <xacro:if value="${mass == -1}">
        <xacro:property name="volume" value="${length * width * plate_thickness}"/>
        <xacro:property name="mass" value="${volume * density}"/>
      </xacro:if>

      <!-- It may make more sense to have origin in center of thickness, but when you export as cade, usally is done from edge -->
      <link name="${name}">

      <visual>
          <origin xyz="0 ${origin_offset} ${plate_thickness/2}" rpy="0 0 0"/>
          <geometry>
              <box size="${width} ${length} ${plate_thickness}"/>
          </geometry>
          <material name="${material}"/>
      </visual>

      <collision>
          <origin xyz="0 ${origin_offset} ${plate_thickness/2}" rpy="0 0 0"/>
          <geometry>
              <box size="${width} ${length} ${plate_thickness}"/>
          </geometry>
      </collision>

      <xacro:solid_cuboid_inertial width="${width}" height="${length}" depth="${plate_thickness}" mass="${mass}" origin_xyz="0 ${origin_offset} ${plate_thickness/2}"/>
      </link>
      
  </xacro:macro>


  <!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia#:~:text=Solid%20cuboid%20of%20width -->
  <!-- Inertia properties for wrist_link, scoped to this macro only -->
  <!-- Width goes along x, height goes along y, depth goes along z -->
  <xacro:macro name="solid_cuboid_inertial" params="width height depth mass origin_xyz">
      <xacro:property name="inertia_xx" value="${(1/12) * mass * (height * height + depth * depth)}"/>
      <xacro:property name="inertia_yy" value="${(1/12) * mass * (width * width + depth * depth)}"/>
      <xacro:property name="inertia_zz" value="${(1/12) * mass * (width * width + height * height)}"/>
      <inertial>
          <origin xyz="${origin_xyz}"/>
          <mass value="${mass}"/>
          <inertia ixx="${inertia_xx}" ixy="0" ixz="0"
                    iyy="${inertia_yy}" iyz="0"
                    izz="${inertia_zz}"/>
      </inertial>
  </xacro:macro>

  <!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia#:~:text=%5D-,Solid%20cylinder%20of,-radius%20r%2C%20height -->
  <!-- Inertia properties for motor block, scoped to this macro only -->
  <!-- I initally thought it should be outer_radius - inner_radius, but actually a hollow cylinder should have a higher interia! as more mass further away -->
  <xacro:macro name="cylinder_inertial" params="length outer_radius mass origin_xyz inner_radius=0">
      <xacro:property name="inertia_xx" value="${(1/12) * mass * (3*(outer_radius*outer_radius + inner_radius*inner_radius) + length*length)}"/>
      <xacro:property name="inertia_yy" value="${(1/12) * mass * (3*(outer_radius*outer_radius + inner_radius*inner_radius) + length*length)}"/>
      <xacro:property name="inertia_zz" value="${0.5*mass*(outer_radius*outer_radius + inner_radius*inner_radius)}"/>
      <inertial>
          <origin xyz="${origin_xyz}"/>
          <mass value="${mass}"/>
          <inertia ixx="${inertia_xx}" ixy="0" ixz="0"
                    iyy="${inertia_yy}" iyz="0"
                    izz="${inertia_zz}"/>
      </inertial>
  </xacro:macro>

<xacro:macro name="dummy_inertial">
<!-- Super small interia to not effect dynamics and small rviz interia box -->
    <inertial>
        <mass value="0.0001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia 
            ixx="0.001" ixy="0.00001" ixz="0.00001"
            iyy="0.001" iyz="0.00001"
            izz="0.001"/>
    </inertial>
</xacro:macro>

<xacro:macro name="dummy_link">

  <!-- Small visual box so that link can be turned off in rviz -->
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.001 0.001 0.001"/>
    </geometry>
    <material name="transparent_gray">
      <color rgba="0.5 0.5 0.5 0.1"/>
    </material>
  </visual>

  <xacro:dummy_inertial/>

</xacro:macro>

  <material name="StoglRobotics/Violet">
    <color rgba="${102/255} ${46/255} ${145/255} 1.0"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="StoglRobotics/DarkGrey">
    <color rgba="${51/255} ${51/255} ${51/255} 1.0"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="StoglRobotics/LightGrey">
    <color rgba="${194/255} ${194/255} ${194/255} 1.0"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Ghost">
    <color rgba="${194/255} ${194/255} ${194/255} 0.5"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Black">
    <color rgba="${0/255} ${0/255} ${0/255} 1"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="White">
    <color rgba="${255/255} ${255/255} ${255/255} 1"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>


  <material name="Red">
    <color rgba="1.0 0.0 0.0 1.0"/>
    <ambient>1 0 0 1</ambient>
    <diffuse>1 0 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Orange">
    <color rgba="1.0 0.55 0.0 1.0"/>
    <ambient>1 0.5 0 1</ambient>
    <diffuse>1 0.5 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Yellow">
    <color rgba="1.0 1.0 0.0 1.0"/>
    <ambient>1 1 0 1</ambient>
    <diffuse>1 1 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Green">
    <color rgba="0.0 1.0 0.0 1.0"/>
    <ambient>0 1 0 1</ambient>
    <diffuse>0 1 0 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 1.0 1.0"/>
    <ambient>0 0 1 1</ambient>
    <diffuse>0 0 1 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Indigo">
    <color rgba="0.29 0.0 0.51 1.0"/>
    <ambient>0.25 0 0.45 1</ambient>
    <diffuse>0.25 0 0.45 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

  <material name="Violet">
    <color rgba="0.56 0.0 1.0 1.0"/>
    <ambient>0.5 0 1 1</ambient>
    <diffuse>0.5 0 1 1</diffuse>
    <specular>0.1 0.1 0.1 1</specular>
    <emissive>0 0 0 0</emissive>
  </material>

</robot>