<?xml version="1.0"?>
<robot name="one_dof_pendulum" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Material definitions -->
  <material name="motor_housing">
    <color rgba="0.5 0.5 0.5 0.3"/>
  </material>
  
  <material name="motor_core">
    <color rgba="0.1 0.4 0.8 1.0"/> <!-- blueish -->
  </material>
  
  <material name="gearbox">
    <color rgba="0.8 0.7 0.1 1.0"/> <!-- yellow/gold -->
  </material>
  
  <material name="arm">
    <color rgba="0.2 0.8 0.2 1.0"/> <!-- green -->
  </material>
  
  <material name="payload">
    <color rgba="0.8 0.2 0.7 1.0"/> <!-- magenta/pink -->
  </material>

  <!-- Constants -->
  <xacro:arg name="arm_length" default="0.25"/>
  <xacro:arg name="payload_mass" default="0.1"/>
  <xacro:arg name="arm_mass" default="0.1"/>

  <!-- Parameter definitions for easy adjustment -->
  <xacro:property name="motor_diameter" value="0.05"/>
  <xacro:property name="motor_radius" value="${motor_diameter/2}"/>
  <xacro:property name="motor_length" value="0.03"/>
  <xacro:property name="motor_mass" value="0.04"/>
  <xacro:property name="motor_inertia_zz" value="${10**2 * (0.58/100**2)}"/> <!-- J_load = N**2 * J_motor and kg*cm^2 -> kg*m^2 -->
  <xacro:property name="motor_inertia_xx_yy" value="${motor_inertia_zz * (0.5 + (motor_length**2/(6*motor_radius**2)))}"/> <!-- given the zz, calculate the xx and yy -->

  <xacro:property name="gearbox_diameter" value="0.04"/>
  <xacro:property name="gearbox_radius" value="${gearbox_diameter/2}"/>
  <xacro:property name="gearbox_length" value="0.02"/>
  <xacro:property name="gearbox_mass" value="0.04"/>
  <xacro:property name="gearbox_inertia_zz" value="${0.13/100**2}"/> <!-- kg*cm^2 -> kg*m^2 -->
  <xacro:property name="gearbox_inertia_xx_yy" value="${gearbox_inertia_zz * (0.5 + (gearbox_length**2/(6*gearbox_radius**2)))}"/> <!-- given the zz, calculate the xx and yy -->

  <xacro:property name="arm_width" value="0.015"/>
  <xacro:property name="arm_length" value="$(arg arm_length)"/>
  <xacro:property name="arm_mass" value="$(arg arm_mass)"/>
  <xacro:property name="arm_inertia_xx_zz" value="${(1/12) * arm_mass * arm_length **2}"/>

  <xacro:property name="payload_diameter" value="0.04"/>
  <xacro:property name="payload_radius" value="${payload_diameter/2}"/>
  <xacro:property name="payload_thickness" value="0.02"/>
  <xacro:property name="payload_mass" value="$(arg payload_mass)"/>
  <!-- You don't acctually need the parrallel axis thoerm, urdf iwll handle that! -->
  <xacro:property name="payload_inertia_zz" value="${(0.5 * payload_mass * payload_radius**2)}"/> <!-- interia + parrallel axis theorem -->
  <xacro:property name="payload_inertia_xx_yy" value="${((1/12) * payload_mass * (3*payload_radius**2 + payload_thickness**2))}"/> <!-- interia + parrallel axis theorem -->


  <link name="base_link"/>

  <link name="motor_housing">
    <visual>
      <geometry>
        <box size="${motor_diameter*1.2} ${motor_diameter*1.2} ${motor_length}"/>
      </geometry>
      <material name="motor_housing"/>
    </visual>
  </link>

  <joint name="base_link_to_motor_housing" type="fixed">
    <parent link="base_link"/>
    <child link="motor_housing"/>
    <origin xyz="0 0 0.0" rpy="${pi/2} 0 0"/>
  </joint>
  
  <!-- Motor core cylinder -->
  <link name="motor_core">
    <visual>
      <geometry>
        <cylinder radius="${motor_diameter/2}" length="${motor_length}"/>
      </geometry>
      <material name="motor_core"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_diameter/2}" length="${motor_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${motor_mass}"/>
      <inertia ixx="${motor_inertia_xx_yy}" ixy="0" ixz="0" 
                iyy="${motor_inertia_xx_yy}" iyz="0" 
                izz="${motor_inertia_zz}"/>
    </inertial>

  </link>

  <!-- Joint connecting motor core to base -->
  <joint name="joint_1" type="revolute">
    <parent link="motor_housing"/>
    <child link="motor_core"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14159" upper="3.14159" effort="10" velocity="5"/>
  </joint>

  <!-- Gearbox cylinder -->
  <link name="gearbox">
    <visual>
      <geometry>
        <cylinder radius="${gearbox_diameter/2}" length="${gearbox_length}"/>
      </geometry>
      <material name="gearbox"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${gearbox_diameter/2}" length="${gearbox_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${gearbox_mass}"/>
      <inertia ixx="${gearbox_inertia_xx_yy}" ixy="0" ixz="0" 
                iyy="${gearbox_inertia_xx_yy}" iyz="0"
                izz="${gearbox_inertia_zz}"/>
    </inertial>
  </link>

  <!-- Joint connecting gearbox to motor core -->
  <joint name="gearbox_joint" type="fixed">
    <parent link="motor_core"/>
    <child link="gearbox"/>
    <origin xyz="0 0 ${gearbox_length/2 + motor_length/2}" rpy="0 0 0"/>
  </joint>

  <!-- Pendulum arm (thin rectangular link) -->
  <link name="arm">
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <box size="${arm_width} ${arm_width} ${arm_length}"/>
      </geometry>
      <material name="arm"/>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <box size="${arm_width} ${arm_width} ${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${arm_length/2} 0 0"/>
      <mass value="${arm_mass}"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" 
                iyy="${arm_inertia_xx_zz}" iyz="0" 
                izz="${arm_inertia_xx_zz}"/>
    </inertial>
  </link>

  <!-- Joint connecting pendulum arm to gearbox (revolute joint) -->
  <joint name="gearbox_to_arm" type="fixed">
    <parent link="gearbox"/>
    <child link="arm"/>
    <origin xyz="0 0 ${gearbox_length/2 + arm_width/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14159" upper="3.14159" effort="10" velocity="5"/>
    <!-- Zero position is when pendulum is pointing down -->
  </joint>

  <!-- Weight disk at the end of pendulum -->
  <link name="payload">
    <visual>
      <geometry>
        <cylinder radius="${payload_diameter/2}" length="${payload_thickness}"/>
      </geometry>
      <material name="payload"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${payload_diameter/2}" length="${payload_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${payload_mass}"/>
      <inertia ixx="${payload_inertia_xx_yy}" ixy="0" ixz="0"
                    iyy="${payload_inertia_xx_yy}" iyz="0"
                    izz="${payload_inertia_zz}"/>
    </inertial>
  </link>

  <!-- Joint connecting payload to pendulum arm -->
  <joint name="arm_to_payload" type="fixed">
    <parent link="arm"/>
    <child link="payload"/>
    <origin xyz="${arm_length} 0 ${payload_thickness/2 + arm_width/2}" rpy="0 0 0"/>
  </joint>

</robot>
